import KaotikaUser from '../interfaces/KaotikaUser';

enum MockedPlayer {
  ACOLYTE,
  NON_ACOLYTE,
}

const mockedPlayers: KaotikaUser[] = [
  {
    _id: '1234567890abcdef',
    is_in_tower_entrance: false,
    is_inside_tower: true,
    active: true,
    rol: 'acolyte',
    socketId: 'socket1234',
    isInside: true,
    attributes: {
      intelligence: 18,
      dexterity: 10,
      charisma: 14,
      constitution: 12,
      strength: 8,
      insanity: 4,
      resistance: 100,
    },
    equipment: {
      helmet: {
        _id: 'helmet001',
        name: 'Crown of the Acolyte',
        description: 'A crown imbued with spiritual energy.',
        type: 'helmet',
        image: 'crown_acolyte.png',
        value: 150,
        min_lvl: 5,
        modifiers: {
          intelligence: 3,
          dexterity: 0,
          charisma: 2,
          constitution: 0,
          strength: 0,
          insanity: -1,
        },
        defense: 5,
        isUnique: true,
        isActive: true,
      },
      weapon: {
        _id: 'weapon001',
        name: 'Staff of the Divine',
        description:
          'A staff that channels divine energy for healing and protection.',
        type: 'weapon',
        image: 'staff_divine.png',
        value: 200,
        min_lvl: 6,
        modifiers: {
          intelligence: 5,
          dexterity: 0,
          charisma: 3,
          constitution: 0,
          strength: 1,
          insanity: 0,
        },
        base_percentage: 50,
        die_faces: 4,
        die_modifier: 1,
        die_num: 1,
        isUnique: true,
        isActive: true,
      },
      armor: {
        _id: 'armor001',
        name: 'Robe of the Acolyte',
        description:
          'A robe that provides moderate protection while enhancing magical powers.',
        type: 'armor',
        image: 'robe_acolyte.png',
        value: 120,
        min_lvl: 4,
        modifiers: {
          intelligence: 2,
          dexterity: 0,
          charisma: 1,
          constitution: 2,
          strength: 0,
          insanity: 0,
        },
        defense: 8,
        isUnique: false,
        isActive: true,
      },
      shield: {
        _id: 'shield001',
        name: 'Divine Shield',
        description:
          'A shield blessed with divine energy to protect the faithful.',
        type: 'shield',
        image: 'shield_divine.png',
        value: 150,
        min_lvl: 5,
        modifiers: {
          intelligence: 1,
          dexterity: 0,
          charisma: 2,
          constitution: 3,
          strength: 0,
          insanity: -1,
        },
        defense: 10,
        isUnique: true,
        isActive: true,
      },
      artifact: {
        _id: 'artifact001',
        name: 'Holy Relic',
        description:
          "A powerful artifact that enhances the acolyte's healing abilities.",
        type: 'artifact',
        image: 'holy_relic.png',
        value: 250,
        min_lvl: 6,
        modifiers: {
          intelligence: 4,
          dexterity: 0,
          charisma: 2,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        isActive: true,
        isUnique: true,
      },
      boot: {
        _id: 'boot001',
        name: 'Boots of Lightness',
        description:
          'Light boots that allow the acolyte to move swiftly and silently.',
        type: 'boot',
        image: 'boots_lightness.png',
        value: 100,
        min_lvl: 3,
        modifiers: {
          intelligence: 0,
          dexterity: 3,
          charisma: 0,
          constitution: 1,
          strength: 0,
          insanity: 0,
        },
        defense: 3,
        isUnique: false,
        isActive: true,
      },
      ring: {
        _id: 'ring001',
        name: 'Ring of Blessing',
        description:
          'A ring that grants the acolyte divine protection and healing power.',
        type: 'ring',
        image: 'ring_blessing.png',
        value: 130,
        min_lvl: 4,
        modifiers: {
          intelligence: 3,
          dexterity: 0,
          charisma: 1,
          constitution: 1,
          strength: 0,
          insanity: 0,
        },
        isActive: true,
        isUnique: true,
      },
      antidote_potion: {
        _id: 'antidote001',
        name: 'Antidote of Purity',
        description: 'A potion that cures poison and harmful effects.',
        type: 'antidote',
        image: 'antidote_purity.png',
        value: 50,
        min_lvl: 1,
        recovery_effect: {
          _id: 'recovery001',
          modifiers: {
            intelligence: 0,
            dexterity: 0,
            charisma: 0,
            constitution: 5,
            strength: 0,
            insanity: 0,
            hit_points: 20,
          },
          name: 'Cure Poison',
          description: 'Removes poison and restores a small amount of health.',
          type: 'recovery',
          antidote_effects: ['cure_poison'],
          poison_effects: ['none'],
        },
      },
      healing_potion: {
        _id: 'healing001',
        name: 'Healing Potion',
        description: 'A potion that restores a significant amount of health.',
        type: 'healing_potion',
        image: 'healing_potion.png',
        value: 80,
        min_lvl: 2,
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 5,
          strength: 0,
          insanity: 0,
          hit_points: 40,
        },
      },
      enhancer_potion: {
        _id: 'enhancer001',
        name: 'Potion of Enlightenment',
        description:
          "A potion that temporarily boosts the acolyte's wisdom and clarity.",
        type: 'enhancer_potion',
        image: 'enhancer_potion.png',
        value: 100,
        min_lvl: 4,
        modifiers: {
          intelligence: 5,
          dexterity: 0,
          charisma: 2,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        duration: 120,
      },
    },
    inventory: {
      helmets: [],
      weapons: [],
      armors: [],
      shields: [],
      artifacts: [],
      boots: [],
      rings: [],
      antidote_potions: [],
      healing_potions: [],
      enhancer_potions: [],
      ingredients: [],
    },
    name: 'Elysia',
    nickname: 'The Blessed',
    email: 'elysia@kaotika.com',
    avatar: 'elysia_avatar.png',
    classroom_Id: 'classroom101',
    level: 12,
    experience: 1500,
    is_active: true,
    profile: {
      _id: 'profile001',
      name: 'Elysia',
      description: 'A devoted acolyte, a healer and protector of the divine.',
      image: 'elysia_profile.png',
      attributes: [
        {
          _id: 'attr001',
          name: 'Wisdom',
          description: 'Increases magical potency',
          value: 18,
        },
        {
          _id: 'attr002',
          name: 'Dexterity',
          description: 'Improves agility and evasiveness',
          value: 10,
        },
        {
          _id: 'attr003',
          name: 'Charisma',
          description: 'Enhances influence and communication',
          value: 14,
        },
        {
          _id: 'attr004',
          name: 'Constitution',
          description: 'Increases physical endurance',
          value: 12,
        },
      ],
    },
    tasks: [
      {
        _id: 'task001',
        classroomId: 'classroom101',
        courseWorkName: 'Healing Spells 101',
        grade: 90,
        selectedAssignment: 'Lecture Notes',
        maxPoints: 100,
      },
      {
        _id: 'task002',
        classroomId: 'classroom101',
        courseWorkName: 'Divine Protection',
        grade: 85,
        selectedAssignment: 'Healing Practice',
        maxPoints: 100,
      },
    ],
    gold: 350,
    created_date: '2025-11-26T10:00:00Z',
    isBetrayer: false,
    skills: [
      { _id: 'skill001', skill: 'Healing Touch', activeLevels: [1, 2, 3] },
      { _id: 'skill002', skill: 'Divine Shield', activeLevels: [1, 2] },
    ],
    pushToken: 'push_token_1234',
    card_id: 'card1234',
    has_been_summoned_to_hos: false,
    has_completed_artifacts_search: false,
    is_inside_hs: false,
    found_artifacts: [],
  },
  {
    _id: '1234567890abc999',
    is_in_tower_entrance: false,
    is_inside_tower: true,
    active: true,
    rol: 'mortimer',
    socketId: 'socket_mortimer_01',
    isInside: true,
    attributes: {
      intelligence: 18,
      dexterity: 10,
      charisma: 14,
      constitution: 12,
      strength: 8,
      insanity: 4,
    },
    equipment: {
      helmet: {
        _id: 'helmet_mort_001',
        name: 'Crown of Mortimer',
        description: 'A crown radiating an eerie and ancient influence.',
        type: 'helmet',
        image: 'crown_mortimer.png',
        value: 150,
        min_lvl: 5,
        modifiers: {
          intelligence: 3,
          dexterity: 0,
          charisma: 2,
          constitution: 0,
          strength: 0,
          insanity: -1,
        },
        defense: 5,
        isUnique: true,
        isActive: true,
      },
      weapon: {
        _id: 'weapon_mort_001',
        name: 'Mortimer’s Staff',
        description: 'A staff used to channel obscure, forgotten knowledge.',
        type: 'weapon',
        image: 'staff_mortimer.png',
        value: 200,
        min_lvl: 6,
        modifiers: {
          intelligence: 5,
          dexterity: 0,
          charisma: 3,
          constitution: 0,
          strength: 1,
          insanity: 0,
        },
        base_percentage: 50,
        die_faces: 4,
        die_modifier: 1,
        die_num: 1,
        isUnique: true,
        isActive: true,
      },
      armor: {
        _id: 'armor_mort_001',
        name: 'Mortimer’s Robe',
        description:
          'A robe that strengthens occult insight while offering protection.',
        type: 'armor',
        image: 'robe_mortimer.png',
        value: 120,
        min_lvl: 4,
        modifiers: {
          intelligence: 2,
          dexterity: 0,
          charisma: 1,
          constitution: 2,
          strength: 0,
          insanity: 0,
        },
        defense: 8,
        isUnique: false,
        isActive: true,
      },
      shield: {
        _id: 'shield_mort_001',
        name: 'Shield of the Forgotten',
        description: 'A protective relic infused with old rites.',
        type: 'shield',
        image: 'shield_forgotten.png',
        value: 150,
        min_lvl: 5,
        modifiers: {
          intelligence: 1,
          dexterity: 0,
          charisma: 2,
          constitution: 3,
          strength: 0,
          insanity: -1,
        },
        defense: 10,
        isUnique: true,
        isActive: true,
      },
      artifact: {
        _id: 'artifact_mort_001',
        name: 'Relic of Whispered Voices',
        description:
          'A mysterious artifact that amplifies Mortimer’s arcane control.',
        type: 'artifact',
        image: 'relic_whispers.png',
        value: 250,
        min_lvl: 6,
        modifiers: {
          intelligence: 4,
          dexterity: 0,
          charisma: 2,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        isActive: true,
        isUnique: true,
      },
      boot: {
        _id: 'boot_mort_001',
        name: 'Boots of Silence',
        description:
          'These boots allow Mortimer to move without making a sound.',
        type: 'boot',
        image: 'boots_silence.png',
        value: 100,
        min_lvl: 3,
        modifiers: {
          intelligence: 0,
          dexterity: 3,
          charisma: 0,
          constitution: 1,
          strength: 0,
          insanity: 0,
        },
        defense: 3,
        isUnique: false,
        isActive: true,
      },
      ring: {
        _id: 'ring_mort_001',
        name: 'Ring of Pale Insight',
        description: 'This ring grants Mortimer subtle protection and clarity.',
        type: 'ring',
        image: 'ring_pale_insight.png',
        value: 130,
        min_lvl: 4,
        modifiers: {
          intelligence: 3,
          dexterity: 0,
          charisma: 1,
          constitution: 1,
          strength: 0,
          insanity: 0,
        },
        isActive: true,
        isUnique: true,
      },
      antidote_potion: {
        _id: 'antidote_mort_001',
        name: 'Antidote of Purity',
        description: 'A potion that cures poison and harmful effects.',
        type: 'antidote',
        image: 'antidote_purity.png',
        value: 50,
        min_lvl: 1,
        recovery_effect: {
          _id: 'recovery_mort_001',
          modifiers: {
            intelligence: 0,
            dexterity: 0,
            charisma: 0,
            constitution: 5,
            strength: 0,
            insanity: 0,
            hit_points: 20,
          },
          name: 'Cure Poison',
          description: 'Removes poison and restores a small amount of health.',
          type: 'recovery',
          antidote_effects: ['cure_poison'],
          poison_effects: ['none'],
        },
      },
      healing_potion: {
        _id: 'healing_mort_001',
        name: 'Healing Potion',
        description: 'A potion that restores a significant amount of health.',
        type: 'healing_potion',
        image: 'healing_potion.png',
        value: 80,
        min_lvl: 2,
        modifiers: {
          intelligence: 0,
          dexterity: 0,
          charisma: 0,
          constitution: 5,
          strength: 0,
          insanity: 0,
          hit_points: 40,
        },
      },
      enhancer_potion: {
        _id: 'enhancer_mort_001',
        name: 'Potion of Enlightenment',
        description: 'A potion that briefly heightens Mortimer’s perception.',
        type: 'enhancer_potion',
        image: 'enhancer_potion.png',
        value: 100,
        min_lvl: 4,
        modifiers: {
          intelligence: 5,
          dexterity: 0,
          charisma: 2,
          constitution: 0,
          strength: 0,
          insanity: 0,
        },
        duration: 120,
      },
    },
    inventory: {
      helmets: [],
      weapons: [],
      armors: [],
      shields: [],
      artifacts: [],
      boots: [],
      rings: [],
      antidote_potions: [],
      healing_potions: [],
      enhancer_potions: [],
      ingredients: [],
    },
    name: 'Mortimer',
    nickname: 'The Pale Scholar',
    email: 'mortimer@kaotika.com',
    avatar: 'mortimer_avatar.png',
    classroom_Id: 'classroom101',
    level: 12,
    experience: 1500,
    is_active: true,
    profile: {
      _id: 'profile_mort_001',
      name: 'Mortimer',
      description: 'An obscure scholar who seeks forbidden knowledge.',
      image: 'mortimer_profile.png',
      attributes: [
        {
          _id: 'attr_mort_001',
          name: 'Wisdom',
          description: 'Increases magical potency',
          value: 18,
        },
        {
          _id: 'attr_mort_002',
          name: 'Dexterity',
          description: 'Improves agility and evasiveness',
          value: 10,
        },
        {
          _id: 'attr_mort_003',
          name: 'Charisma',
          description: 'Enhances influence and communication',
          value: 14,
        },
        {
          _id: 'attr_mort_004',
          name: 'Constitution',
          description: 'Increases physical endurance',
          value: 12,
        },
      ],
    },
    tasks: [
      {
        _id: 'task_mort_001',
        classroomId: 'classroom101',
        courseWorkName: 'Forgotten Rites',
        grade: 90,
        selectedAssignment: 'Occult Notes',
        maxPoints: 100,
      },
      {
        _id: 'task_mort_002',
        classroomId: 'classroom101',
        courseWorkName: 'Mystic Barriers',
        grade: 85,
        selectedAssignment: 'Protection Ritual',
        maxPoints: 100,
      },
    ],
    gold: 350,
    created_date: '2025-11-26T10:00:00Z',
    isBetrayer: false,
    skills: [
      { _id: 'skill_mort_001', skill: 'Occult Touch', activeLevels: [1, 2, 3] },
      { _id: 'skill_mort_002', skill: 'Ethereal Shield', activeLevels: [1, 2] },
    ],
    pushToken: 'push_token_mortimer',
    card_id: 'card_mort_999',
    has_been_summoned_to_hos: false,
    has_completed_artifacts_search: false,
    is_inside_hs: false,
    found_artifacts: [],
  },
];

export { MockedPlayer, mockedPlayers };
